// Content for info sections
export const homeObjOne = {
    id: "about-us",
    lightBG: false,
    topText: true,
    lightText: true,
    lightTextDesc: true,
    topLine: "About Us",
    headline: "Who are we?",
    description: "Experienced advisors that assist in helping you make efficient decisions as you grow and develop your business.",
    buttonLabel: "Learn more",
    imgStart: false,
    img: ("../../images/svg-1.svg"),
    alt: "Shake Hands",
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjTwo = {
    id: "effective-solutions",
    lightBG: true,
    topText: false,
    lightText: false,
    lightTextDesc: false,
    topLine: "Effective Solutions",
    headline: "Why do I need a consultant?",
    description: "The challenge for many founders is making the leap from converting an idea into a business. We stand in the gap to help new founders, creators, and seasoned entrepreneurs develop custom solutions that tackle key questions.",
    buttonLabel: "Learn more",
    imgStart: true,
    img: ("../../images/svg-2.svg"),
    alt: "Growth Analytics",
    dark: false,
    primary: false,
    darkText: true,
}

export const homeObjThree = {
    id: "decision-making",
    lightBG: false,
    topText: true,
    lightText: true,
    lightTextDesc: true,
    topLine: "Decision Making",
    headline: "What can our consultants do for you?",
    description: "As a small business owner, you are constantly faced with making impactful decisions for your business.  Our consultants leverage their experience to help you make effective decisions that bring you closer to your goals.",
    buttonLabel: "Learn more",
    imgStart: false,
    img: ("../../images/svg-3.svg"),
    alt: "Small Business",
    dark: true,
    primary: true,
    darkText: false,
}